### ISSUE TITLE
State covariance matrix update

### ISSUE THREAD

**Issue by gke** [har-in-air/Kalmanfilter_altimeter_vario#1]
I am using your code in my flight controller. I believe the state covariance matrix update should be reversed as the new P values are being overwritten e.g. Pzz is computed and then used to update Paz.

I think the ordering should be:

	Paz -= ka * Pzz;
	Pav -= ka * Pzv;
	Paa -= ka * Pza;

	Pvz -= kv * Pzz;
	Pvv -= kv * Pzv;
	Pva -= kv * Pza;

	Pzz -= kz * Pzz;
	Pzv -= kz * Pzv;
	Pza -= kz * Pza;

Cheers

**Comment by romatou18** [comment]
> I am using your code in my flight controller. I believe the state covariance matrix update should be reversed as the new P values are being overwritten e.g. Pzz is computed and then used to update Paz.
> 
> I think the ordering should be:
> 
> ```
> Paz -= ka * Pzz;
> Pav -= ka * Pzv;
> Paa -= ka * Pza;
> 
> Pvz -= kv * Pzz;
> Pvv -= kv * Pzv;
> Pva -= kv * Pza;
> 
> Pzz -= kz * Pzz;
> Pzv -= kz * Pzv;
> Pza -= kz * Pza;
> ```
> 
> Cheers

That's a great point. Do you think you coukd create a branch and then a merge/pull request. It would ensure that this change gets through and with the best understanding and implementation.

Regards

**Comment by har-in-air** [comment]
Greg Egan, I have made the changes. Thanks for the code review !
