### ISSUE TITLE
Bug in KalmanFilter.cpp

### ISSUE THREAD

**Issue by reza1376** [har-in-air/Kalmanfilter_altimeter_vario#2]
Hi I think something wrong in " Update state covariance matrix"
        Paz -= ka * Pzz;
	Pav -= ka * Pzv;
	Paa -= ka * Pza;

	Pvz -= kv * Pzz;
	Pvv -= kv * Pzv;
	Pva -= kv * Pza;

	Pzz -= kz * Pzz;
	Pzv -= kz * Pzv;
	Pza -= kz * Pza;
must be 
        Paz_ -= ka * Pzz_;
	Pav_ -= ka * Pzv_;
	Paa_ -= ka * Pza_;

	Pvz_ -= kv * Pzz_;
	Pvv_ -= kv * Pzv_;
	Pva_ -= kv * Pza_;

	Pzz_ -= kz * Pzz_;
	Pzv_ -= kz * Pzv_;
	Pza_ -= kz * Pza_;

**Comment by har-in-air** [comment]
Fixed, thanks for letting me know.  My actual implementation projects using the filter are ok.
regardsHari
    On Wednesday, 17 June, 2020, 12:14:13 am IST, reza1376 <notifications@github.com> wrote:  
 
 


Hi I think something wrong in " Update state covariance matrix"
Paz -= ka * Pzz;
Pav -= ka * Pzv;
Paa -= ka * Pza;
Pvz -= kv * Pzz;
Pvv -= kv * Pzv;
Pva -= kv * Pza;

Pzz -= kz * Pzz;
Pzv -= kz * Pzv;
Pza -= kz * Pza;

must be
Paz_ -= ka * Pzz_;
Pav_ -= ka * Pzv_;
Paa_ -= ka * Pza_;
Pvz_ -= kv * Pzz_;
Pvv_ -= kv * Pzv_;
Pva_ -= kv * Pza_;

Pzz_ -= kz * Pzz_;
Pzv_ -= kz * Pzv_;
Pza_ -= kz * Pza_;
